/**: 
  ros__parameters:
    velocity_threshold_kmh: 5.0       
    merge_frequency_hz: 10.0  
    #it means that if the message is not received within this time, it will be considered as timeout  
    # total timeout = message_timeout_sec + 1000 / merge_frequency_hz  ~ 150 ms
    message_timeout_sec: 0.05   
    merge_frame: "base_link"        

    radar_topics: [
      "/sensing/radar/front_center/detected_objects",
      "/sensing/radar/front_left/detected_objects",
      "/sensing/radar/front_right/detected_objects",
      "/sensing/radar/rear_center/detected_objects",
      "/sensing/radar/rear_left/detected_objects",
      "/sensing/radar/rear_right/detected_objects"

    ]

    front_center_radar_topic: "/sensing/radar/front_center/detected_objects"

